routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\StatsController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\PariController;
use App\Http\Controllers\JoueurController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\Bet_mController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource("users",UserController::class);
Route::resource("stats",StatsController::class);
Route::resource("profils",ProfilController::class);
Route::resource("paris",PariController::class);
Route::resource("joueurs",JoueurController::class);
Route::resource("infos",InfoController::class);
Route::resource("bet_ms",Bet_mController::class);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Profil.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Profil extends Model
{
    use HasFactory;

    /**
     * Get the user that owns the phone.
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/ProfilController.php
<?php

namespace App\Http\Controllers;

use App\Models\Profil;
use Illuminate\Http\Request;

class ProfilController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $profils = Profil::paginate(5)->fragment('profils');

        return view('profils.index',['profils'=>$profils]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('profils.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function show(Profil $profil)
    {
        // dd($profil);
        $data = Profil::findOrFail($profil->id);

        return view('profils.show',['profil'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function edit(Profil $profil)
    {
        return view('profils.edit',['profil'=>$profil]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Profil $profil)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Profil  $profil
     * @return \Illuminate\Http\Response
     */
    public function destroy(Profil $profil)
    {
        Profil::findOrFail($profil->id)->delete();

        return view('profils');
    }
}

resources/views/profils/create.blade.php
@extends('layouts.profils')

@section('title')

@section('container')
    <div class="form">
        <form action="{{route('profils.store')}}" method="POST">
            @csrf
            
            <span>
                <button type="submit">Send</button>
                <button type="reset">Reset</button>
            </span>
        </form>
    </div>
@endsection

resources/views/profils/edit.blade.php
@extends('layouts.profils')

@section('title')

@section('container')
    <div class="form">
        <form action="{{route('profils.update',['profil'=>$profil])}}" method="POST">
            @csrf
            @method('PUT')
            
            <span>
                <button type="submit">Update</button>
                <button type="reset">Reset</button>
            </span>
        </form>
    </div>
@endsection

resources/views/profils/index.blade.php
@extends('layouts.profils')

@section('title')
    
@endsection

@section('container')
    <div class="container">
        @forelse ($profils as $profil)
            <h3>
                <a href="{{ route('profils.show',['profil'=>$profil->id])}}">{{ $profil->nom}}</a>
                <a href="{{route('profils.edit',['profil'=>$profil->id])}}">Edit</a>
                <form action="{{route('profils.destroy',['profil'=>$profil->id])}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit">Delete</button>
                </form>
            </h3>
        @empty
            <h3>No Merritz profil found !!!</h3>
        @endforelse
    </div> 
    {{ $profils->links() }}
@endsection

 

resources/views/profils/show.blade.php
@extends('layouts.profils')

@section('title')
    
@endsection

@section('container')
    <div class="container">
        <div>nom : {{$profil->nom}}</div>
        <div>prenom : {{$profil->prenom}}</div>
        <div>email : {{$profil->email}}</div>
        <div>sexe : {{$profil->sexe}}</div>
    </div> 
@endsection

 