routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\StatsController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\PariController;
use App\Http\Controllers\JoueurController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\Bet_mController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::resource("users",UserController::class);
Route::resource("stats",StatsController::class);
Route::resource("profils",ProfilController::class);
Route::resource("paris",PariController::class);
Route::resource("joueurs",JoueurController::class);
Route::resource("infos",InfoController::class);
Route::resource("bet_ms",Bet_mController::class);

Route::get('/', function () {
    return view('welcome');
});

app/Models/Stats.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stats extends Model
{
    use HasFactory;
}

app/Http/Controllers/StatsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Stats;
use Illuminate\Http\Request;

class StatsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // dd('ok');
        $stats = Stats::paginate(5)->fragment('stats');

        return view('stats.index',['stats'=>$stats]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('stats.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Stats  $stats
     * @return \Illuminate\Http\Response
     */
    public function show(Stats $stats)
    {
        dd($stats);
       $stat = Stats::findOrFail($stats->id);

       return view('stats.show',['stat'=>$stat]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Stats  $stats
     * @return \Illuminate\Http\Response
     */
    public function edit(Stats $stats)
    {
        return view('stats.edit',['stat'=>$stats]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Stats  $stats
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Stats $stats)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Stats  $stats
     * @return \Illuminate\Http\Response
     */
    public function destroy(Stats $stats)
    {
        dd($stats);
        Stats::findOrFail($stats->id)->delete();

        return redirect('users');
    }
}

resources/views/stats/create.blade.php
@extends('layouts.stats')

@section('title')

@section('container')
    <div class="form">
        <form action="{{route('stats.store')}}" method="POST">
            @csrf
            
            <span>
                <button type="submit">Send</button>
                <button type="reset">Reset</button>
            </span>
        </form>
    </div>
@endsection

resources/views/stats/edit.blade.php
@extends('layouts.stats')

@section('title')

@section('container')
    <div class="form">
        <form action="{{route('stats.update',['stat'=>$stat])}}" method="POST">
            @csrf
            @method('PUT')
            <input type="text" name="login" id="login" value="{{$stat->login}}">
            <label for="login">Login</label><br>
            <input type="text" name="password" id="password" value="{{$stat->password}}">
            <label for="password">password</label><br>
            <span>
                <button type="submit">Update</button>
                <button type="reset">Reset</button>
            </span>
        </form>
    </div>
@endsection

resources/views/stats/index.blade.php
@extends('layouts.stats')

@section('title')
    
@endsection

@section('container')
    <div class="container">
        @forelse ($stats as $stat)
            <h3>
                <a href="{{ route('stats.show',['stat'=>$stat->id])}}">{{ $stat->login}}</a>
                <a href="{{route('stats.edit',['stat'=>$stat->id])}}">Edit</a>
                <form action="{{route('stats.destroy',['stat'=>$stat->id])}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button type="submit">Delete</button>
                </form>
            </h3>
        @empty
            <h3>No Merritz stat found !!!</h3>
        @endforelse
    </div> 
    {{ $stats->links() }}
@endsection

 

resources/views/stats/show.blade.php
@extends('layouts.stats')

@section('title')
    
@endsection

@section('container')
    <div class="container">
        stats...
    </div> 
@endsection

 